config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :events, only: [:create, :show]
  resources :home, only: [:index]
  resources :activities, only: [:create]
  resources :participants, only: [:create]
  resources :attendances, only: [:update]
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :attendances, dependent: :destroy
  has_many :participants, through: :attendances
  belongs_to :event

  validates :name, presence: true
  validates :scheduled_at, uniqueness: true, presence: true
  default_scope { order(scheduled_at: :asc) }

  after_create :add_attendances

  def add_attendances
    return if event.participants.empty?
    event.participants.each do |participant|
      attendances.create(participant_id: participant.id, activity_id: self.id)
    end
  end
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :activity
  belongs_to :participant
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :activities
  has_many :participants

  before_save :generate_slug

  accepts_nested_attributes_for :activities, :participants

  def to_param
    self.slug
  end

  def generate_slug
    self.slug ||= [*('A'..'Z')].sample(8).join
  end
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :event
  has_many :attendances, dependent: :destroy
  has_many :activities, through: :attendances

  validates :name, presence: true

  after_create :add_attendances

  def add_attendances
    return if event.activities.empty?
    event.activities.each do |activity|
      attendances.create(activity_id: activity.id, participant_id: self.id)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events, dependent: :destroy
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def create
    activity = Activity.new(activity_params)
    if activity.save
      respond_to do |format|
        format.json { render json: EventSerializer.new(activity.event).as_json['event'] }
      end
    else
      respond_to do |format|
        format.json { render(json: "Something went wrong, please try again", status: :unprocessable_entity) }
      end
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :scheduled_at, :event_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def update
    attendance = Attendance.find params[:id]
    attendance.toggle!(:attending)

    render json: EventSerializer.new(attendance.activity.event)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
    event = Event.new(event_params)
    if event.save
      redirect_to event_path(event.slug), notice: "'#{event.name}' has been added"
    else
      redirect_to :back, alert: 'Something went wrong - Event has not been created'
    end
  end

  def show
    @event = Event.find_by(slug: params[:id])
    event_serializer = EventSerializer.new(@event).as_json

    @serialized_event = event_serializer['event']

    respond_to do |format|
      format.html
      format.json { render json: @serialized_event }
    end
  end

  private

  def event_params
    params.require(:event).permit(
      :user_id,
      :name,
      :date,
      :description,
      activities_attributes: [:name, :scheduled_at],
      participants_attributes: [:name]
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @event = Event.new
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def create
    participant = Participant.new(participant_params)
    if participant.save
      respond_to do |format|
        format.json { render json: EventSerializer.new(participant.event).as_json['event'] }
      end
    else
      respond_to do |format|
        format.json { render(json: "Please enter a name", status: :unprocessable_entity) }
      end
    end
  end

  private

  def participant_params
    params.require(:participant).permit(:name, :activity_id, :attending, :event_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_planner_helper.rb
module EventPlannerHelper
end

app/views/events/index.html.haml
.container
  .col-md-8.col-md-offset-2
    .panel.panel-primary
      .panel-heading
        %h3.panel-title Create an event
      .panel-body
        = form_for :event do |f|
          .form-group
            = f.label :name
            = f.text_field :name, class: 'form-control'
          .form-group
            = f.label :date
            = f.text_field :date, class: 'datepicker form-control'
          = f.submit 'Save', class: 'btn btn-default'

.container
  .col-md-8.col-md-offset-2
    .panel.panel-primary
      .panel-heading
        %h3.panel-title Events
      %table.table
        %thead
          %th.text-center Name
          %th.text-center date
          %th.text-center Edit
          %th.text-center Delete
        %tbody
          - @events.each do |event|
            %tr
              = form_for :event, url: event_path(event), method: :put do |f|
                = f.hidden_field :id, value: event.id
                %td.text-center= f.text_field :name, value: event.name, class: 'form-control'
                %td.text-center= f.text_field :date, class: 'datepicker form-control', value: event.date.strftime("%d/%m/%Y")
                %td.text-center= f.submit 'Save', class: 'btn btn-warning'
                %td.text-center= link_to 'delete', event, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } 

app/views/events/show.html.haml
- content_for :body_classes, ' event-planner '

.container
  .row
    .col-md-12
      = react_component('EventsTable', event: @serialized_event, url: request.url)

app/views/home/index.html.haml
- content_for :body_classes, 'homepage '

.banner.text-center
  .container
    .col-sm-12
      .main-title
        Schmoogle
        %span.logo.fa.fa-calendar
        Planner

      .sub-header
        Scheduling simplified

      %button.btn.btn-home{ data: { toggle: 'modal', target: '#get-started' }} Get started

.container
  .col-sm-12
    .row
      .col-sm-4
        .section
          .description-icon.text-center
            .fa.fa-calendar-check-o
          .text-center
            Bacon ipsum dolor amet meatball leberkas sausage swine. Boudin andouille biltong strip steak chuck. T-bone flank kielbasa pig. Sausage landjaeger chuck drumstick. Cupim prosciutto capicola sirloin alcatra pig. Ball tip leberkas sausage, shoulder pork loin ham hock pork venison boudin.
      .col-sm-4
        .section
          .description-icon.text-center
            .fa.fa-pencil-square-o
          .text-center
            Pork loin turducken brisket andouille biltong. Landjaeger prosciutto t-bone tenderloin beef ribs boudin bresaola pancetta picanha sirloin. Landjaeger rump tri-tip pork chop pork loin. Shankle cupim flank ham hock strip steak.
      .col-sm-4
        .section
          .description-icon.text-center
            .fa.fa-users
          .text-center
            Picanha beef flank turducken ball tip pork belly pastrami kielbasa. Pork loin frankfurter meatloaf, t-bone short loin turkey drumstick shoulder leberkas pork spare ribs tail filet mignon prosciutto pastrami.

= render 'home/partials/get_started'

app/views/home/partials/_get_started.html.haml
.modal.fade#get-started{ tabindex: "-1", role:"dialog" }
  .modal-dialog
    .modal-content
      #get-started-content
        .modal-header
          %h4 Create your event
        .modal-body
          .row
            .col-md-12
              = form_for @event, url: events_path do |f|
                = f.fields_for :activities, @event.activities.new do |a|
                  = f.fields_for :participants, @event.participants.new do |p|
                    .form-group
                      = p.label :name,'Your name'
                      = p.text_field :name, class: 'form-control'
                    %hr
                    .form-group
                      = f.label :name,'Event name'
                      = f.text_field :name, class: 'form-control'
                      = f.label :date,'Event date'
                      = f.date_field :date, class: 'form-control'
                      = f.label :description,'Event description'
                      = f.text_area :description, class: 'form-control'
                    %hr
                    .form-group
                      = a.label :name, 'Activity name'
                      = a.text_field :name, class: 'form-control'
                      = a.label :scheduled_at, 'Scheduled at'
                      = a.time_field :scheduled_at, class: 'form-control'

                    = f.button "Create event", class: "btn btn-info"

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Schmoogle
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    %link{ rel:"stylesheet", href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"}

    %script{ src: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"}
    %script{ src: "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.js"}
    %script{ src: "https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.js"}

    %link{ href: 'https://fonts.googleapis.com/css?family=Great+Vibes|Poiret+One|Roboto:400,300,100', rel: 'stylesheet', type: 'text/css' }
    %link{ rel: "stylesheet", href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"}
    %link{ rel: "stylesheet", href: "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css"}
    %link{ rel: "stylesheet", href: "https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.css"}

  %body{class: content_for(:body_classes)}
    %header
      %nav.navbar.navbar-default
        .container
          .navbar-header
            = link_to "/", class: "navbar-brand" do
              Schmoogle
              %span.logo.fa.fa-calendar
              Planner

    = yield